site:
  title: ODIP
  url: http://localhost:8081
  start_page: odip:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD

antora:
  extensions:
    - '@antora/lunr-extension'
    - require: './antora-docx-extension.js'
      assembler_config: ./antora-assembler-docx.yml

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    page-pagination: ''