openapi: 3.0.3

info:
  title: ODP REST API / ODP Edition Management
  description: ODP Edition Management Operations for the Operational Deployment Plan Management API
  version: 1.0.0
  contact:
    name: ODP Development Team

paths:
  # ODP Edition CRUD Endpoints
  /odp-editions:
    get:
      summary: List all ODP editions
      tags: [ODP]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'openapi-base.yml#/components/schemas/ODPEdition'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

    post:
      summary: Create new ODP edition
      tags: [ODP]
      description: |
        Creates a new ODP Edition by referencing an existing baseline and specifying 
        a starting wave. The edition provides a filtered view of the baseline content
        based on the wave timeline.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'openapi-base.yml#/components/schemas/ODPEditionRequest'
      responses:
        '201':
          description: ODP Edition created successfully
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/ODPEdition'
        '400':
          description: Bad Request - Invalid baseline or wave reference
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

  /odp-editions/{id}:
    get:
      summary: Get ODP edition by ID
      tags: [ODP]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ODP Edition ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/ODPEdition'
        '404':
          description: ODP Edition not found
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

  /odp-editions/{id}/export:
    get:
      summary: Export ODP edition as AsciiDoc
      tags: [ODP]
      description: |
        Exports a specific ODP Edition as an AsciiDoc document. The export includes
        all waves, milestones, and deliverables associated with the edition, formatted
        as a structured AsciiDoc document suitable for documentation generation.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ODP Edition ID
      responses:
        '200':
          description: Success - AsciiDoc document
          content:
            text/plain:
              schema:
                type: string
                description: AsciiDoc formatted document
        '404':
          description: ODP Edition not found
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

  /odp-editions/export:
    get:
      summary: Export entire repository as AsciiDoc
      tags: [ODP]
      description: |
        Exports the entire ODP repository as an AsciiDoc document. This includes
        all editions with their associated waves, milestones, and deliverables,
        organized in a comprehensive document structure.
      responses:
        '200':
          description: Success - AsciiDoc document
          content:
            text/plain:
              schema:
                type: string
                description: AsciiDoc formatted document containing all editions
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'