openapi: 3.0.3

info:
  title: ODP REST API / Operational Milestones
  description: Operational Change Milestones Management Operations for the Operational Deployment Plan Management API
  version: 1.0.0
  contact:
    name: ODP Development Team

paths:
  # Milestone CRUD Endpoints
  /operational-changes/{id}/milestones:
    get:
      summary: List all milestones for operational change
      tags: [Milestones]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Operational Change ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'openapi-base.yml#/components/schemas/Milestone'
        '404':
          description: Operational Change not found
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

    post:
      summary: Add milestone to operational change (creates new OC version)
      tags: [Milestones]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Operational Change ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'openapi-base.yml#/components/schemas/MilestoneUpdateRequest'
      responses:
        '201':
          description: Milestone created
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Milestone'
        '409':
          description: Version Conflict
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

  /operational-changes/{id}/milestones/{milestoneId}:
    get:
      summary: Get specific milestone
      tags: [Milestones]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Operational Change ID
        - name: milestoneId
          in: path
          required: true
          schema:
            type: string
          description: Milestone ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Milestone'
        '404':
          description: Milestone or Operational Change not found
          content:
            application/json:
              schema:
                $ref: 'openapi-base.yml#/components/schemas/Error'

    put:
      summary: Update milestone (creates new OC version)
      tags: [Milestones]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Operational Change ID
        - name: milestoneId
          in: path
          required: true
          schema:
            type: string
          description: Milestone ID