components:
  securitySchemes:
    UserContext:
      type: apiKey
      in: header
      name: X-User-ID

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string

    EntityReference:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        note:
          type: string

    OperationalRequirementReference:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string
          enum: [ON, OR]

    # Setup Entity Schemas
    StakeholderCategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        parentCategory:
          $ref: '#/components/schemas/EntityReference'
        childCategories:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'

    StakeholderCategoryRequest:
      type: object
      required: [name, description]
      properties:
        name:
          type: string
        description:
          type: string
        parentCategoryId:
          type: string
          nullable: true

    DataCategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        parentCategory:
          $ref: '#/components/schemas/EntityReference'
        childCategories:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'

    DataCategoryRequest:
      type: object
      required: [name, description]
      properties:
        name:
          type: string
        description:
          type: string
        parentCategoryId:
          type: string
          nullable: true

    Service:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        parentService:
          $ref: '#/components/schemas/EntityReference'
        childServices:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'

    ServiceRequest:
      type: object
      required: [name, description]
      properties:
        name:
          type: string
        description:
          type: string
        parentServiceId:
          type: string
          nullable: true

    Document:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        url:
          type: string
          nullable: true

    DocumentRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
        version:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        url:
          type: string
          nullable: true

    Wave:
      type: object
      properties:
        id:
          type: string
        year:
          type: integer
        quarter:
          type: integer
        date:
          type: string
          format: date
        name:
          type: string
          description: "Wave name in format 'year.quarter' (e.g., '2025.1')"

    WaveRequest:
      type: object
      required: [year, quarter, date]
      properties:
        year:
          type: integer
          minimum: 2024
          maximum: 2030
        quarter:
          type: integer
          minimum: 1
          maximum: 4
        date:
          type: string
          format: date

    # Operational Entity Schemas
    OperationalRequirement:
      type: object
      properties:
        itemId:
          type: string
        title:
          type: string
        versionId:
          type: string
        version:
          type: integer
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        type:
          type: string
          enum: [ON, OR]
        statement:
          type: string
        rationale:
          type: string
        flows:
          type: string
        privateNotes:
          type: string
        path:
          type: array
          items:
            type: string
        drg:
          type: string
          enum: [4DT, AIRPORT, ASM_ATFCM, CRISIS_FAAS, FLOW, IDL, NM_B2B, NMUI, PERF, RRT, TCF]
        refinesParents:
          type: array
          items:
            $ref: '#/components/schemas/OperationalRequirementReference'
        impactsStakeholderCategories:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
        impactsData:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
        impactsServices:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
        implementedONs:
          type: array
          items:
            $ref: '#/components/schemas/OperationalRequirementReference'
          description: "ON-type requirements implemented by this OR (OR type only)"
        dependsOnRequirements:
          type: array
          items:
            type: string
          description: "Requirement item IDs (follows latest version automatically) this requirement depends on"
        documentReferences:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'

    OperationalRequirementRequest:
      type: object
      required: [title, type, statement, rationale, flows]
      properties:
        title:
          type: string
        type:
          type: string
          enum: [ON, OR]
        statement:
          type: string
        rationale:
          type: string
        flows:
          type: string
        privateNotes:
          type: string
        path:
          type: array
          items:
            type: string
        drg:
          type: string
          enum: [4DT, AIRPORT, ASM_ATFCM, CRISIS_FAAS, FLOW, IDL, NM_B2B, NMUI, PERF, RRT, TCF]
        refinesParents:
          type: array
          items:
            type: string
          default: []
        impactsStakeholderCategories:
          type: array
          items:
            type: string
          default: []
        impactsData:
          type: array
          items:
            type: string
          default: []
        impactsServices:
          type: array
          items:
            type: string
          default: []
        implementedONs:
          type: array
          items:
            type: string
          default: []
          description: "ON-type requirement Item IDs (OR type only)"
        dependsOnRequirements:
          type: array
          items:
            type: string
          default: []
          description: "Requirement item IDs (follows latest version automatically)"
        documentReferences:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
          default: []

    OperationalRequirementUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/OperationalRequirementRequest'
        - type: object
          required: [expectedVersionId]
          properties:
            expectedVersionId:
              type: string

    OperationalRequirementPatchRequest:
      type: object
      required: [expectedVersionId]
      properties:
        expectedVersionId:
          type: string
        title:
          type: string
        type:
          type: string
          enum: [ON, OR]
        statement:
          type: string
        rationale:
          type: string
        flows:
          type: string
        privateNotes:
          type: string
        path:
          type: array
          items:
            type: string
        drg:
          type: string
          enum: [4DT, AIRPORT, ASM_ATFCM, CRISIS_FAAS, FLOW, IDL, NM_B2B, NMUI, PERF, RRT, TCF]
        refinesParents:
          type: array
          items:
            type: string
        impactsStakeholderCategories:
          type: array
          items:
            type: string
        impactsData:
          type: array
          items:
            type: string
        impactsServices:
          type: array
          items:
            type: string
        implementedONs:
          type: array
          items:
            type: string
        dependsOnRequirements:
          type: array
          items:
            type: string
        documentReferences:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'

    Milestone:
      type: object
      properties:
        id:
          type: string
        milestoneKey:
          type: string
          description: "Stable UUID identifier preserved across versions"
        title:
          type: string
        description:
          type: string
        eventType:
          type: string
          enum: [API_PUBLICATION, API_TEST_DEPLOYMENT, UI_TEST_DEPLOYMENT, OPS_DEPLOYMENT, API_DECOMMISSIONING]
        targetDate:
          type: string
          format: date
        actualDate:
          type: string
          format: date
          nullable: true
        wave:
          $ref: '#/components/schemas/Wave'

    MilestoneRequest:
      type: object
      required: [title, eventType]
      properties:
        title:
          type: string
        description:
          type: string
        eventType:
          type: string
          enum: [API_PUBLICATION, API_TEST_DEPLOYMENT, UI_TEST_DEPLOYMENT, OPS_DEPLOYMENT, API_DECOMMISSIONING]
        targetDate:
          type: string
          format: date
        actualDate:
          type: string
          format: date
          nullable: true
        waveId:
          type: string

    OperationalChange:
      type: object
      properties:
        itemId:
          type: string
        title:
          type: string
        versionId:
          type: string
        version:
          type: integer
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        purpose:
          type: string
        initialState:
          type: string
        finalState:
          type: string
        details:
          type: string
        privateNotes:
          type: string
        path:
          type: array
          items:
            type: string
        visibility:
          type: string
          enum: [NM, NETWORK]
        drg:
          type: string
          enum: [4DT, AIRPORT, ASM_ATFCM, CRISIS_FAAS, FLOW, IDL, NM_B2B, NMUI, PERF, RRT, TCF]
        satisfiesRequirements:
          type: array
          items:
            $ref: '#/components/schemas/OperationalRequirementReference'
        supersedsRequirements:
          type: array
          items:
            $ref: '#/components/schemas/OperationalRequirementReference'
        dependsOnChanges:
          type: array
          items:
            type: string
          description: "Change item IDs (follows latest version automatically) this change depends on"
        documentReferences:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
        milestones:
          type: array
          items:
            $ref: '#/components/schemas/Milestone'

    OperationalChangeRequest:
      type: object
      required: [title, purpose, visibility]
      properties:
        title:
          type: string
        purpose:
          type: string
        initialState:
          type: string
        finalState:
          type: string
        details:
          type: string
        privateNotes:
          type: string
        path:
          type: array
          items:
            type: string
        visibility:
          type: string
          enum: [NM, NETWORK]
        drg:
          type: string
          enum: [4DT, AIRPORT, ASM_ATFCM, CRISIS_FAAS, FLOW, IDL, NM_B2B, NMUI, PERF, RRT, TCF]
        satisfiesRequirements:
          type: array
          items:
            type: string
          default: []
        supersedsRequirements:
          type: array
          items:
            type: string
          default: []
        dependsOnChanges:
          type: array
          items:
            type: string
          default: []
          description: "Change item IDs (follows latest version automatically)"
        documentReferences:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
          default: []
        milestones:
          type: array
          items:
            $ref: '#/components/schemas/MilestoneRequest'
          default: []

    OperationalChangeUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/OperationalChangeRequest'
        - type: object
          required: [expectedVersionId]
          properties:
            expectedVersionId:
              type: string

    OperationalChangePatchRequest:
      type: object
      required: [expectedVersionId]
      properties:
        expectedVersionId:
          type: string
        title:
          type: string
        purpose:
          type: string
        initialState:
          type: string
        finalState:
          type: string
        details:
          type: string
        privateNotes:
          type: string
        path:
          type: array
          items:
            type: string
        visibility:
          type: string
          enum: [NM, NETWORK]
        drg:
          type: string
          enum: [4DT, AIRPORT, ASM_ATFCM, CRISIS_FAAS, FLOW, IDL, NM_B2B, NMUI, PERF, RRT, TCF]
        satisfiesRequirements:
          type: array
          items:
            type: string
        supersedsRequirements:
          type: array
          items:
            type: string
        dependsOnChanges:
          type: array
          items:
            type: string
        documentReferences:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
        milestones:
          type: array
          items:
            $ref: '#/components/schemas/MilestoneRequest'

    VersionHistory:
      type: object
      properties:
        versionId:
          type: string
        version:
          type: integer
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string

    # Management Entity Schemas
    Baseline:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string

    BaselineRequest:
      type: object
      required: [title]
      properties:
        title:
          type: string

    ODPEdition:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string
          enum: [ALPHA, BETA, RELEASE]
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        baseline:
          $ref: '#/components/schemas/EntityReference'
        startsFromWave:
          $ref: '#/components/schemas/EntityReference'

    ODPEditionRequest:
      type: object
      required: [title, type, baselineId, startsFromWaveId]
      properties:
        title:
          type: string
        type:
          type: string
          enum: [ALPHA, BETA, RELEASE]
        baselineId:
          type: string
        startsFromWaveId:
          type: string