openapi: 3.0.3
info:
  title: ODP REST API
  description: Operational Deployment Plan Management API
  version: 1.0.0
  contact:
    name: ODP Development Team

servers:
  - url: http://localhost
    description: Development server

security:
  - UserContext: []

# Import schemas and components from base file
components:
  $ref: 'openapi-base.yml#/components'

# Combine all paths from separate files
paths:
  # Setup entity endpoints
  /stakeholder-categories:
    $ref: 'openapi-setup.yml#/paths/~1stakeholder-categories'
  /stakeholder-categories/{id}:
    $ref: 'openapi-setup.yml#/paths/~1stakeholder-categories~1{id}'

  /data-categories:
    $ref: 'openapi-setup.yml#/paths/~1data-categories'
  /data-categories/{id}:
    $ref: 'openapi-setup.yml#/paths/~1data-categories~1{id}'

  /services:
    $ref: 'openapi-setup.yml#/paths/~1services'
  /services/{id}:
    $ref: 'openapi-setup.yml#/paths/~1services~1{id}'

  /regulatory-aspects:
    $ref: 'openapi-setup.yml#/paths/~1regulatory-aspects'
  /regulatory-aspects/{id}:
    $ref: 'openapi-setup.yml#/paths/~1regulatory-aspects~1{id}'

  /waves:
    $ref: 'openapi-setup.yml#/paths/~1waves'
  /waves/{id}:
    $ref: 'openapi-setup.yml#/paths/~1waves~1{id}'

  # Operational entity endpoints
  /operational-requirements:
    $ref: 'openapi-operational.yml#/paths/~1operational-requirements'
  /operational-requirements/{id}:
    $ref: 'openapi-operational.yml#/paths/~1operational-requirements~1{id}'
  /operational-requirements/{id}/versions:
    $ref: 'openapi-operational.yml#/paths/~1operational-requirements~1{id}~1versions'
  /operational-requirements/{id}/versions/{versionNumber}:
    $ref: 'openapi-operational.yml#/paths/~1operational-requirements~1{id}~1versions~1{versionNumber}'

  /operational-changes:
    $ref: 'openapi-operational.yml#/paths/~1operational-changes'
  /operational-changes/{id}:
    $ref: 'openapi-operational.yml#/paths/~1operational-changes~1{id}'
  /operational-changes/{id}/versions:
    $ref: 'openapi-operational.yml#/paths/~1operational-changes~1{id}~1versions'
  /operational-changes/{id}/versions/{versionNumber}:
    $ref: 'openapi-operational.yml#/paths/~1operational-changes~1{id}~1versions~1{versionNumber}'

  # Milestone endpoints
  /operational-changes/{id}/milestones:
    $ref: 'openapi-operational-milestones.yml#/paths/~1operational-changes~1{id}~1milestones'
  /operational-changes/{id}/milestones/{milestoneId}:
    $ref: 'openapi-operational-milestones.yml#/paths/~1operational-changes~1{id}~1milestones~1{milestoneId}'

  # Baseline management endpoints
  /baselines:
    $ref: 'openapi-baseline.yml#/paths/~1baselines'
  /baselines/{id}:
    $ref: 'openapi-baseline.yml#/paths/~1baselines~1{id}'

tags:
  - name: Stakeholder Categories
    description: Stakeholder category management
  - name: Data Categories
    description: Data category management
  - name: Services
    description: Services management
  - name: Regulatory Aspects
    description: Regulatory aspect management
  - name: Waves
    description: Waves management for deployment timelines
  - name: Operational Requirements
    description: Operational requirement management with versioning
  - name: Operational Changes
    description: Operational change management with versioning
  - name: Milestones
    description: Milestone management within operational changes
  - name: Baselines
    description: Baseline management for deployment planning