component_versions: '**'
asciidoc:
  attributes:
    allow-uri-read: ''
    source-highlighter: rouge
    toc: ''
    toclevels: 3
    sectnums: ''
    sectnumlevels: 7
    version-label: 'Edition'
    env-export: ''
build:
  command: asciidoctor -b docbook